export const searchDTOResponseExample = {
  number: 0,
  size: 7,
  total: 5908,
  content: [
    {
      titulo: 'RRHH',
      tipoTrabajo: 'Full-time',
      logoURL: 'http://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_13075667_bum_vd40f98b7.jpg',
      empresa: 'NavarroARG',
      localizacion: 'Ituzaingó, Buenos Aires',
      fechaPublicacion: '08-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      planPublicacion: {
        id: 10,
        nombre: 'Home',
      },
      confidencial: false,
      portal: 'Bumeran',
      oportunidad: false,
      fechaHoraPublicacion: '08-08-2019 11:37:49',
      idEmpresa: 13075667,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/application/avisos/1113483256',
        },
      ],
      id: 1113483256,
    },
    {
      titulo: 'Asistente de Gerencia',
      tipoTrabajo: 'Full-time',
      logoURL:
        'http://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_13075667_aviso_1113483255_bum_vaf337268.jpg',
      empresa: 'Iunigo',
      localizacion: 'Ituzaingó, Buenos Aires',
      fechaPublicacion: '08-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      planPublicacion: {
        id: 10,
        nombre: 'Home',
      },
      confidencial: false,
      portal: 'Bumeran',
      oportunidad: false,
      fechaHoraPublicacion: '08-08-2019 11:31:43',
      idEmpresa: 13075667,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/application/avisos/1113483255',
        },
      ],
      id: 1113483255,
    },
    {
      titulo: 'Ejecutivo de Ventas',
      tipoTrabajo: 'Full-time',
      logoURL:
        'http://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_13075667_aviso_1113483254_bum_v70f3971b.jpg',
      empresa: 'Big Blue',
      localizacion: 'Ituzaingó, Buenos Aires',
      fechaPublicacion: '08-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      planPublicacion: {
        id: 40,
        nombre: 'Destacados',
      },
      confidencial: false,
      portal: 'Bumeran',
      oportunidad: false,
      fechaHoraPublicacion: '08-08-2019 11:30:33',
      idEmpresa: 13075667,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/application/avisos/1113483254',
        },
      ],
      id: 1113483254,
    },
    {
      titulo: 'Asistente de Gerencia',
      tipoTrabajo: 'Full-time',
      logoURL:
        'http://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_13075667_aviso_1113483252_bum_v629c36d4.jpg',
      empresa: 'Médicos sin fronteras',
      localizacion: 'Ituzaingó, Buenos Aires',
      fechaPublicacion: '08-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      planPublicacion: {
        id: 10,
        nombre: 'Home',
      },
      confidencial: false,
      portal: 'Bumeran',
      oportunidad: false,
      fechaHoraPublicacion: '08-08-2019 11:25:01',
      idEmpresa: 13075667,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/application/avisos/1113483252',
        },
      ],
      id: 1113483252,
    },
    {
      titulo: 'Call Center',
      tipoTrabajo: 'Full-time',
      logoURL:
        'http://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_13075667_aviso_1113483251_bum_v914330ff.jpg',
      empresa: 'Solventa',
      localizacion: 'Ituzaingó, Buenos Aires',
      fechaPublicacion: '08-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      planPublicacion: {
        id: 40,
        nombre: 'Destacados',
      },
      confidencial: false,
      portal: 'Bumeran',
      oportunidad: false,
      fechaHoraPublicacion: '08-08-2019 11:23:53',
      idEmpresa: 13075667,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/application/avisos/1113483251',
        },
      ],
      id: 1113483251,
    },
    {
      titulo: 'Vendedor Telefonico',
      tipoTrabajo: 'Full-time',
      logoURL: 'http://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_13075667_bum_vd40f98b7.jpg',
      empresa: 'NavarroARG',
      localizacion: 'Ituzaingó, Buenos Aires',
      fechaPublicacion: '08-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      planPublicacion: {
        id: 10,
        nombre: 'Home',
      },
      confidencial: false,
      portal: 'Bumeran',
      oportunidad: false,
      fechaHoraPublicacion: '08-08-2019 11:21:07',
      idEmpresa: 13075667,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/application/avisos/1113483249',
        },
      ],
      id: 1113483249,
    },
    {
      titulo: 'Administracion',
      tipoTrabajo: 'Full-time',
      logoURL: 'http://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_13075667_bum_vd40f98b7.jpg',
      empresa: 'NavarroARG',
      localizacion: 'Ituzaingó, Buenos Aires',
      fechaPublicacion: '08-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      planPublicacion: {
        id: 40,
        nombre: 'Destacados',
      },
      confidencial: false,
      portal: 'Bumeran',
      oportunidad: false,
      fechaHoraPublicacion: '08-08-2019 11:20:01',
      idEmpresa: 13075667,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/application/avisos/1113483248',
        },
      ],
      id: 1113483248,
    },
  ],
}
