export const listadoMock = {
  number: 0,
  size: 30,
  total: 2361,
  content: [
    {
      titulo: 'Programador | Desarrolladores/ Programador De Software',
      tipoTrabajo: 'Full-time',
      logoURL: null,
      empresa: 'Humanitas IT Recursos Humanos',
      localizacion: 'Córdoba, Córdoba',
      fechaPublicacion: '24-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: true,
      detalle:
        ' Dividato es una Nearshore Software Company que brinda servicios de desarrollo y staff augmentation a compañías de USA, UE y LATAM. Sede en córdoba capital, argentina. Las búsquedas varían en los',
      planPublicacion: {
        id: 2001,
        nombre: 'Freemium',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '24-08-2019 15:10:00',
      idEmpresa: 13175685,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113522762',
        },
      ],
      id: 1113522762,
    },
    {
      titulo: 'Programador de Automatización / Desarrollador de software de control:',
      tipoTrabajo: 'Full-time',
      logoURL: null,
      empresa: 'Confidencial',
      localizacion: 'El Talar, Buenos Aires',
      fechaPublicacion: '22-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' control de PLC, accionamientos, HMI, SCADA, DCS, software de gestión. Puesta en servicio de equipos y líneas de producción. Cumplimiento de tiempos y plazos de desarrollo y puesta en servicio.  Trabajo a',
      planPublicacion: {
        id: 40,
        nombre: 'Destacados',
      },
      confidencial: true,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '22-08-2019 08:29:56',
      idEmpresa: 13088798,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113521220',
        },
      ],
      id: 1113521220,
    },
    {
      titulo: 'desarrollador de software/programador .net y/o java y conexos',
      tipoTrabajo: 'Full-time',
      logoURL: null,
      empresa: 'Confidencial',
      localizacion: 'Mendoza, Mendoza',
      fechaPublicacion: '03-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: true,
      detalle:
        ' Importante proyecto tecnológico, selecciona DESARROLLADORES DE SOFTWARE, con o sin expcia. Con conocimientos de .net y/o Java . También se considerará background en: Android , IOS, AWS, Azure',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: true,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '03-09-2019 09:43:55',
      idEmpresa: 13155792,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113545245',
        },
      ],
      id: 1113545245,
    },
    {
      titulo: 'Analista programador',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/0/6/7/4/5/6/0/logoMainPic_674560.jpg',
      empresa: 'S.O.S - Red de Asistencia',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '12-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' SomosSOS Red de Asistenciay nos encontramos en la búsqueda de un analista programador para incorporar a nuestro staff.  Su misión será desarrollar, mantener y brindar soporte a sistemas propios de',
      planPublicacion: {
        id: 40,
        nombre: 'Destacados',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '12-09-2019 08:37:39',
      idEmpresa: 674560,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113565618',
        },
      ],
      id: 1113565618,
    },
    {
      titulo: 'Analistas Programadores',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_13176203_bum_v747b30b4.jpg',
      empresa: 'B&B Consultores',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '30-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Seleccionamos para Rosario y Buenos Aires profesionales con conocimientos en el desarrollo de sistemas ERP y/o sistemas core de Seguros con al menos 3 años de experiencia, manejo de herramientas de',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '30-08-2019 08:28:05',
      idEmpresa: 13176203,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113538823',
        },
      ],
      id: 1113538823,
    },
    {
      titulo: 'Analista Programador Genexus',
      tipoTrabajo: 'Full-time',
      logoURL: null,
      empresa: 'Nomade Soft SRL',
      localizacion: 'Mendoza, Mendoza',
      fechaPublicacion: '13-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle: ' Buscamos analista programador Genexus con experiencia en desarrollos web ',
      planPublicacion: {
        id: 2001,
        nombre: 'Freemium',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '13-09-2019 07:25:00',
      idEmpresa: 13179144,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113562941',
        },
      ],
      id: 1113562941,
    },
    {
      titulo: 'Analista Programador Java ',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '09-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' definir alcances del proyecto. Desarrollar aplicaciones desde cero y también participar en tareas de mantenimiento sobre los sistemas actuales que tiene el cliente.  Requerimientos: Contar con más de 3 años',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '09-09-2019 10:15:10',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113558043',
        },
      ],
      id: 1113558043,
    },
    {
      titulo: 'Analista Programador Java ',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '03-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' definir alcances del proyecto. Desarrollar aplicaciones desde cero y también participar en tareas de mantenimiento sobre los sistemas actuales que tiene el cliente.  Requerimientos: Contar con más de 3 años',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '03-09-2019 07:49:22',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113544577',
        },
      ],
      id: 1113544577,
    },
    {
      titulo: 'Analista Programador Java ',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '29-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' definir alcances del proyecto. Desarrollar aplicaciones desde cero y también participar en tareas de mantenimiento sobre los sistemas actuales que tiene el cliente.  Requerimientos: Contar con más de 3 años',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '29-08-2019 09:43:16',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113536768',
        },
      ],
      id: 1113536768,
    },
    {
      titulo: 'Analista Programador Java ',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '22-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' definir alcances del proyecto. Desarrollar aplicaciones desde cero y también participar en tareas de mantenimiento sobre los sistemas actuales que tiene el cliente.  Requerimientos: Contar con más de 3 años',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '22-08-2019 06:32:20',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113520613',
        },
      ],
      id: 1113520613,
    },
    {
      titulo: 'Analista Programador JAVA - Recoleta',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '09-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' software de acuerdo al de desempeño y conocimientos. Desarrollar aplicaciones desde cero y participar en tareas de mantenimiento sobre los sistemas actuales que tiene el cliente. Requerimientos: Al menos 3',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '09-09-2019 10:14:08',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113558040',
        },
      ],
      id: 1113558040,
    },
    {
      titulo: 'Analista Programador JAVA - Recoleta',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '03-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' software de acuerdo al de desempeño y conocimientos. Desarrollar aplicaciones desde cero y participar en tareas de mantenimiento sobre los sistemas actuales que tiene el cliente. Requerimientos: Al menos 3',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '03-09-2019 07:50:49',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113544590',
        },
      ],
      id: 1113544590,
    },
    {
      titulo: 'Analista Programador JAVA - Recoleta',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '26-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' software de acuerdo al de desempeño y conocimientos. Desarrollar aplicaciones desde cero y participar en tareas de mantenimiento sobre los sistemas actuales que tiene el cliente. Requerimientos: Al menos 3',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '26-08-2019 09:38:03',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113527630',
        },
      ],
      id: 1113527630,
    },
    {
      titulo: 'Analista Programador JAVA - Recoleta',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '20-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' software de acuerdo al de desempeño y conocimientos. Desarrollar aplicaciones desde cero y participar en tareas de mantenimiento sobre los sistemas actuales que tiene el cliente. Requerimientos: Al menos 3',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '20-08-2019 11:53:53',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113516114',
        },
      ],
      id: 1113516114,
    },
    {
      titulo: 'Analista Programador .NET Sr. ',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/1/2/8/4/7/0/0/logoMainPic_1284700.jpg',
      empresa: 'Banco Columbia SA',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '12-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        '. . Requisitos: Ser estudiante o graduado de carreras universitarias o terciarias de Sistemas, Informática o Ciencias de la Computación.  Sólidos conocimientos en desarrollo y mantenimiento de software en .NET',
      planPublicacion: {
        id: 70,
        nombre: 'Simples',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '12-09-2019 07:46:37',
      idEmpresa: 1284700,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113448901',
        },
      ],
      id: 1113448901,
    },
    {
      titulo: 'Analista Programador Jr',
      tipoTrabajo: 'Full-time',
      logoURL: null,
      empresa: 'UFLO',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '10-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Institución educativa  se encuentra  en la búsqueda de un Analista Programador Jr para la Dirección de Sistemas. Se requiere Estudiante de carreras afines, con conocimientos de manejo de base de',
      planPublicacion: {
        id: 70,
        nombre: 'Simples',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '10-09-2019 11:29:17',
      idEmpresa: 400200,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113561219',
        },
      ],
      id: 1113561219,
    },
    {
      titulo: 'Analista Programador Ssr- ',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/1/0/1/8/5/5/3/3/logoMainPic_10185533.jpg',
      empresa: 'WEFOC S.A.',
      localizacion: 'Tapiales, Buenos Aires',
      fechaPublicacion: '13-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Importante Grupo empresarial del ambito del retail, se encuentra en la busqueda de un Analista Programador Ssr para sumar a su equipo de trabajo. Estamos orientados a perfiles con conocimientos en',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '13-09-2019 04:41:02',
      idEmpresa: 10185533,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113349011',
        },
      ],
      id: 1113349011,
    },
    {
      titulo: 'Analista Programador Junior',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/1/3/2/3/8/4/0/logoMainPic_1323840.jpg',
      empresa: 'CATTORINI HNOS S A I C F E I',
      localizacion: 'Avellaneda, Buenos Aires',
      fechaPublicacion: '04-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' CATTORINI HNOS. empresa líder en la fabricación de envases de vidrio, incorpora para el área de Sistemas:  Analista Programador JUNIOR  Incorporamos un PROGRAMADOR JUNIOR, recientemente graduado o',
      planPublicacion: {
        id: 40,
        nombre: 'Destacados',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '04-09-2019 04:23:48',
      idEmpresa: 1323840,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113546828',
        },
      ],
      id: 1113546828,
    },
    {
      titulo: 'Analista Programador .NET',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/0/3/5/7/3/3/0/logoMainPic_357330.jpg',
      empresa: 'Sofrecom',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '21-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' complejos en las diferentes industrias. Estamos seleccionando Analistas Programadores .NET, estudiantes avanzados o graduados de la carrera de sistemas o afines para trabajar a través nuestro en importantes',
      planPublicacion: {
        id: 70,
        nombre: 'Simples',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '21-08-2019 04:29:19',
      idEmpresa: 357330,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1111294620',
        },
      ],
      id: 1111294620,
    },
    {
      titulo: 'Analista Programador .NET - Núñez',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '09-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Para empresa que se dedica al transporte de gas natural por gasoductos de alta presión en el centro y norte de Argentina, estamos buscando un Analista Programador .NET . Habilidades Requeridas',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '09-09-2019 10:44:05',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113558180',
        },
      ],
      id: 1113558180,
    },
    {
      titulo: 'Analista Programador .NET - Núñez',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '05-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Para empresa que se dedica al transporte de gas natural por gasoductos de alta presión en el centro y norte de Argentina, estamos buscando un Analista Programador .NET . Habilidades Requeridas',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '05-09-2019 09:39:34',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113550807',
        },
      ],
      id: 1113550807,
    },
    {
      titulo: 'Analista Programador .NET',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '03-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Para empresa que se dedica al transporte de gas natural por gasoductos de alta presión en el centro y norte de Argentina, estamos buscando un Analista Programador .NET . Habilidades Requeridas',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '03-09-2019 06:54:58',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113544247',
        },
      ],
      id: 1113544247,
    },
    {
      titulo: 'Analista Programador .NET',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '26-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Para empresa que se dedica al transporte de gas natural por gasoductos de alta presión en el centro y norte de Argentina, estamos buscando un Analista Programador .NET . Habilidades Requeridas',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '26-08-2019 08:51:22',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113527380',
        },
      ],
      id: 1113527380,
    },
    {
      titulo: 'Analista Programador .NET',
      tipoTrabajo: 'Full-time',
      logoURL:
        'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/2/6/1/2/3/0/0/logoMainPic_2612300_bum_v979ebb46.jpg',
      empresa: 'Aliantec',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '20-08-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Para empresa que se dedica al transporte de gas natural por gasoductos de alta presión en el centro y norte de Argentina, estamos buscando un Analista Programador .NET . Habilidades Requeridas',
      planPublicacion: {
        id: 1020,
        nombre: 'Aviso Talento',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '20-08-2019 11:22:54',
      idEmpresa: 2612300,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113515989',
        },
      ],
      id: 1113515989,
    },
    {
      titulo: 'Analista Programador PL/SQL',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/0/3/5/7/3/3/0/logoMainPic_357330.jpg',
      empresa: 'Sofrecom',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '09-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' complejos en las diferentes industrias.  Nos encontramos en búsqueda de Analistas Programadores PL/SQL Ssr/Sr, con experiencia comprobable en el puesto de al menos 3 años, para trabajar en un importante',
      planPublicacion: {
        id: 70,
        nombre: 'Simples',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '09-09-2019 12:06:16',
      idEmpresa: 357330,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113558540',
        },
      ],
      id: 1113558540,
    },
    {
      titulo: 'Analista Programador Senior .NET',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_463520_bum_v459905de.jpg',
      empresa: 'ELECTRO CHANCE S.R.L. ',
      localizacion: 'Lomas del Mirador, Buenos Aires',
      fechaPublicacion: '10-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        '  Importante PYME de Zona Oeste de Bs. As. busca: Analista Programador Senior .NET para sumarse a un equipo de trabajo y proyectos de suma importancia para la Empresa. Nos orientamos a un perfil',
      planPublicacion: {
        id: 70,
        nombre: 'Simples',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '10-09-2019 10:40:18',
      idEmpresa: 463520,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113561052',
        },
      ],
      id: 1113561052,
    },
    {
      titulo: 'Analista Programador Junior',
      tipoTrabajo: 'Full-time',
      logoURL: null,
      empresa: 'Mutual Jerarquicos Salud',
      localizacion: 'Santa Fe, Santa Fe',
      fechaPublicacion: '11-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ': Ingeniería Informática o Sistemas, Tecn.Analista de Sistemas.  Beneficios: En Jerárquicos creemos que nuestros colaboradores le agregan valor a nuestra marca empleadora. Es por ello que pensamos en el',
      planPublicacion: {
        id: 70,
        nombre: 'Simples',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '11-09-2019 04:27:03',
      idEmpresa: 1705630,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113489864',
        },
      ],
      id: 1113489864,
    },
    {
      titulo: 'Analista Programador SHAREPOINT',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/0/0/0/0/3/5/7/3/3/0/logoMainPic_357330.jpg',
      empresa: 'Sofrecom',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '13-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' complejos en las diferentes industrias.  Nos encontramos en búsqueda de Analistas Programadores Sharepoint Ssr/Sr para trabajar en un importante proyecto, con experiencia comprobable de al menos 3 años en',
      planPublicacion: {
        id: 70,
        nombre: 'Simples',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '13-09-2019 10:23:59',
      idEmpresa: 357330,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113568600',
        },
      ],
      id: 1113568600,
    },
    {
      titulo: 'ANALISTA PROGRAMADOR SQL SSR',
      tipoTrabajo: 'Full-time',
      logoURL: null,
      empresa: 'Confidencial',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '12-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Compañía especializada en consultoría y servicios en Data Management, ubicada en la zona de Palermo, se encuentra en la búsqueda de un ANALISTA PROGRAMADOR SQL SSR para incorporar a su equipo. La',
      planPublicacion: {
        id: 2001,
        nombre: 'Freemium',
      },
      confidencial: true,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '12-09-2019 08:20:00',
      idEmpresa: 10115481,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113560502',
        },
      ],
      id: 1113560502,
    },
    {
      titulo: 'A- Analista Programador Calipso',
      tipoTrabajo: 'Full-time',
      logoURL: 'https://imgbum.prepro.jobscdn.com/portal/img/empresas/1/static/logoMainPic_444640_bum_vce78c1c9.jpg',
      empresa: 'Grupo Gestión',
      localizacion: 'Capital Federal, Buenos Aires',
      fechaPublicacion: '11-09-2019',
      salarioMinimo: 0,
      salarioMaximo: 0,
      aptoDiscapacitado: false,
      detalle:
        ' Importante empresa incorpora Programador Calipso con experiencia en desarrollo y mantenimiento de software de Gestión y soporte técnico a usuarios internos. debe poseer conocimientos en Calipso',
      planPublicacion: {
        id: 70,
        nombre: 'Simples',
      },
      confidencial: false,
      portal: null,
      oportunidad: false,
      fechaHoraPublicacion: '11-09-2019 12:35:51',
      idEmpresa: 444640,
      fechaPostulacion: null,
      distancia: null,
      estadoPostulacion: null,
      links: [
        {
          rel: 'self',
          href: 'http://bm-applicants.prepro.api.core.jobs.navent.biz/v0/postulantes/avisos/1113564039',
        },
      ],
      id: 1113564039,
    },
  ],
  filters: [
    {
      type: 'nivel_laboral',
      facets: [
        {
          id: '1',
          name: 'Senior / Semi-Senior',
          quantity: 1268,
        },
        {
          id: '2',
          name: 'Junior',
          quantity: 175,
        },
        {
          id: '4',
          name: 'Jefe / Supervisor / Responsable',
          quantity: 138,
        },
        {
          id: '5',
          name: 'Otros',
          quantity: 59,
        },
        {
          id: '3',
          name: 'Gerencia / Alta Gerencia / Dirección',
          quantity: 34,
        },
      ],
    },
    {
      type: 'provincia',
      facets: [
        {
          id: 'buenos-aires',
          name: 'Buenos Aires',
          quantity: 1988,
        },
        {
          id: 'cordoba',
          name: 'Córdoba',
          quantity: 111,
        },
        {
          id: 'santa-fe',
          name: 'Santa Fe',
          quantity: 111,
        },
        {
          id: 'mendoza',
          name: 'Mendoza',
          quantity: 39,
        },
        {
          id: 'neuquen',
          name: 'Neuquén',
          quantity: 23,
        },
        {
          id: 'corrientes',
          name: 'Corrientes',
          quantity: 12,
        },
        {
          id: 'tucuman',
          name: 'Tucumán',
          quantity: 12,
        },
        {
          id: 'san-luis',
          name: 'San Luis',
          quantity: 9,
        },
        {
          id: 'chubut',
          name: 'Chubut',
          quantity: 7,
        },
        {
          id: 'salta',
          name: 'Salta',
          quantity: 7,
        },
        {
          id: 'chaco',
          name: 'Chaco',
          quantity: 6,
        },
        {
          id: 'jujuy',
          name: 'Jujuy',
          quantity: 6,
        },
        {
          id: 'santa-cruz',
          name: 'Santa Cruz',
          quantity: 6,
        },
        {
          id: 'misiones',
          name: 'Misiones',
          quantity: 5,
        },
        {
          id: 'san-juan',
          name: 'San Juan',
          quantity: 5,
        },
        {
          id: 'entre-rios',
          name: 'Entre Ríos',
          quantity: 4,
        },
        {
          id: 'tierra-del-fuego',
          name: 'Tierra del Fuego',
          quantity: 3,
        },
        {
          id: 'rio-negro',
          name: 'Río Negro',
          quantity: 2,
        },
        {
          id: 'la-rioja',
          name: 'La Rioja',
          quantity: 1,
        },
        {
          id: 'santiago-del-estero',
          name: 'Santiago del Estero',
          quantity: 1,
        },
      ],
    },
    {
      type: 'area',
      facets: [
        {
          id: 'tecnologia-sistemas-y-telecomunicaciones',
          name: 'Tecnología, Sistemas y Telecomunicaciones',
          quantity: 934,
        },
        {
          id: 'comercial-ventas-y-negocios',
          name: 'Comercial, Ventas y Negocios',
          quantity: 414,
        },
        {
          id: 'administracion-contabilidad-y-finanzas',
          name: 'Administración, Contabilidad y Finanzas',
          quantity: 231,
        },
        {
          id: 'ingenierias',
          name: 'Ingenierías',
          quantity: 102,
        },
        {
          id: 'produccion-y-manufactura',
          name: 'Producción y Manufactura',
          quantity: 97,
        },
        {
          id: 'abastecimiento-y-logistica',
          name: 'Abastecimiento y Logística',
          quantity: 79,
        },
        {
          id: 'recursos-humanos-y-capacitacion',
          name: 'Recursos Humanos y Capacitación',
          quantity: 68,
        },
        {
          id: 'marketing-y-publicidad',
          name: 'Marketing y Publicidad',
          quantity: 66,
        },
        {
          id: 'atencion-al-cliente-call-center-y-telemarketing',
          name: 'Atención al Cliente, Call Center y Telemarketing',
          quantity: 65,
        },
        {
          id: 'oficios-y-otros',
          name: 'Oficios y Otros',
          quantity: 64,
        },
        {
          id: 'salud-medicina-y-farmacia',
          name: 'Salud, Medicina y Farmacia',
          quantity: 48,
        },
        {
          id: 'ingenieria-civil-y-construccion',
          name: 'Ingeniería Civil y Construcción',
          quantity: 29,
        },
        {
          id: 'diseno',
          name: 'Diseño',
          quantity: 26,
        },
        {
          id: 'gastronomia-y-turismo',
          name: 'Gastronomía y Turismo',
          quantity: 24,
        },
        {
          id: 'mineria-petroleo-y-gas',
          name: 'Minería, Petróleo y Gas',
          quantity: 22,
        },
        {
          id: 'educacion-docencia-e-investigacion',
          name: 'Educación, Docencia e Investigación',
          quantity: 18,
        },
        {
          id: 'comunicacion-relaciones-institucionales-y-publicas',
          name: 'Comunicación, Relaciones Institucionales y Públicas',
          quantity: 15,
        },
        {
          id: 'gerencia-y-direccion-general',
          name: 'Gerencia y Dirección General',
          quantity: 15,
        },
        {
          id: 'seguros',
          name: 'Seguros',
          quantity: 14,
        },
        {
          id: 'legales',
          name: 'Legales',
          quantity: 12,
        },
        {
          id: 'secretarias-y-recepcion',
          name: 'Secretarias y Recepción',
          quantity: 11,
        },
        {
          id: 'aduana-y-comercio-exterior',
          name: 'Aduana y Comercio Exterior',
          quantity: 7,
        },
      ],
    },
    {
      type: 'tipo_trabajo',
      facets: [
        {
          id: 'full-time',
          name: 'Full-time',
          quantity: 2269,
        },
        {
          id: 'part-time',
          name: 'Part-time',
          quantity: 71,
        },
        {
          id: 'pasantia',
          name: 'Pasantia',
          quantity: 12,
        },
        {
          id: 'por-horas',
          name: 'Por Horas',
          quantity: 3,
        },
        {
          id: 'temporario',
          name: 'Temporario',
          quantity: 3,
        },
        {
          id: 'por-contrato',
          name: 'Por Contrato',
          quantity: 2,
        },
        {
          id: 'teletrabajo',
          name: 'Teletrabajo',
          quantity: 1,
        },
      ],
    },
    {
      type: 'dias_fecha_publicacion',
      facets: [
        {
          id: '3',
          name: 'Menor a 3 d&iacute;as',
          quantity: 23,
        },
        {
          id: '4',
          name: 'Menor a 4 días',
          quantity: 57,
        },
        {
          id: '5',
          name: 'Menor a 5 días',
          quantity: 172,
        },
        {
          id: '6',
          name: 'Menor a 6 días',
          quantity: 305,
        },
        {
          id: '7',
          name: 'Menor a 1 semana',
          quantity: 448,
        },
        {
          id: '15',
          name: 'Menor a 15 d&iacute;as',
          quantity: 1162,
        },
        {
          id: '30',
          name: 'Menor a 1 mes',
          quantity: 2361,
        },
      ],
    },
    {
      type: 'apto_discapacitado',
      facets: [
        {
          id: 'apto-discapacitado',
          name: 'Apto personas con discapacidad',
          quantity: 56,
        },
      ],
    },
    {
      type: 'salario',
      facets: [
        {
          id: '*-*',
          name: 'Salario Sin Especificar',
          quantity: 2352,
        },
        {
          id: '8001-*',
          name: '> $8.000',
          quantity: 9,
        },
      ],
    },
  ],
  filtersApplied: [
    {
      id: 'query',
      value: 'programador',
    },
  ],
  extendedTotal: 0,
}
