/*
 * Enum
 */

const ScreenIds = Object.freeze({
  ONBOARDING: 'ONBOARDING',
  BOOT_ERROR: 'BOOT_ERROR',
  HOME: 'HOME',
  MIS_POSTULACIONES: 'MIS_POSTULACIONES',
  CURRICULUM: 'CURRICULUM',
  MENSAJES: 'MENSAJES',
  CHAT: 'CHAT',
  LOGIN: 'LOGIN',
  PRE_LOGIN: 'PRE_LOGIN',
  LISTADO_AVISOS: 'LISTADO_AVISOS',
  FICHA_AVISO: 'FICHA_AVISO',
  PREGUNTAS: 'PREGUNTAS',
  CARTA_PRESENTACION: 'CARTA_PRESENTACION',
  BUSCADOR: 'BUSCADOR',
  AJUSTES: 'AJUSTES',
  INFO: 'INFO',
  NOTIFICACIONES: 'NOTIFICACIONES',
  MI_PERFIL: 'MI_PERFIL',
  DATOS_CONTACTO: 'DATOS_CONTACTO',
  DATOS_PERSONALES: 'DATOS_PERSONALES',
  EDIT_DATOS_CONTACTO: 'EDIT_DATOS_CONTACTO',
  EDIT_DATOS_PERSONALES: 'DATOS_PERSONALES',
  EDIT_EXPERIENCIA_LABORAL: 'EDIT_EXPERIENCIA_LABORAL',
  EDIT_REFERENCIA_LABORAL: 'EDIT_REFERENCIA_LABORAL',
  EDIT_REFERENCIA_EDUCATIVA: 'EDIT_REFERENCIA_EDUCATIVA',
  EDIT_EXPERIENCIA_EDUCATIVA: 'EDIT_EXPERIENCIA_EDUCATIVA',
  EDIT_IDIOMAS: 'EDIT_IDIOMAS',
  MODAL_VIDEO: 'MODAL_VIDEO',
  REGISTRO: 'REGISTRO',
})

/*
 * Exports
 */

export default ScreenIds
